openapi: 3.0.0
info:
  title: Bus Reservation
  description: Bus Reservation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://buspark.scodus.com
    description: Base URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Authentication
  - name: bus schedule
  - name: bus booking
paths:
  /oauth/token:
    post:
      tags:
        - Authentication
      summary: get token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                grant_type: client_credentials
                client_id: 3
                client_secret: xOTYScPsWL8EnfHgkIyqmHpM9lfywn1IfrKyal9f
                scope: '*'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-list:
    get:
      tags:
        - bus schedule
      summary: bus schedule list
      parameters:
        - name: route_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Route Code
          example: ktmmnr100
        - name: association_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Association Code
          example: m100
        - name: date
          in: query
          schema:
            type: string
          description: Schedule Bus Date
          example: '2080-02-32'
        - name: bus_facility_type_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Facility Type Code
          example: ac100
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-bus-detail:
    get:
      tags:
        - bus schedule
      summary: bus schedule bus detail
      parameters:
        - name: route_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Route Code
          example: ktmmnr100
        - name: association_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Association Code
          example: m100
        - name: date
          in: query
          schema:
            type: string
          description: Scheduled Bus Date
          example: '2080-02-32'
        - name: time
          in: query
          schema:
            type: string
          description: Scheduled Bus Time
          example: '19:00'
        - name: bus_facility_type_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Facility Type Code
          example: ac100
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-bus-seats/{bus_schedule_id}:
    get:
      tags:
        - bus schedule
      summary: bus schedule bus seats by bus schedule id
      parameters:
        - name: bus_schedule_id
          in: path
          schema:
            type: integer
          required: true
          description: Scheduled Bus Schedule Id
          example: '100'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/pre-booking:
    get:
      tags:
        - bus booking
      summary: pre booking
      security:
        - bearerAuth: []
      parameters:
        - name: seat_name[]
          in: query
          schema:
            type: string
          description: Bus Seat Name
          example: D
        - name: route_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Route Code
          example: ktmmnr100
        - name: association_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Association Code
          example: m100
        - name: date
          in: query
          schema:
            type: string
          description: Scheduled Bus Date
          example: '2080-02-32'
        - name: time
          in: query
          schema:
            type: string
          description: Scheduled Bus Time
          example: '19:00'
        - name: bus_facility_type_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Facility Type Code
          example: ac100
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/pre-booking-timeout:
    post:
      tags:
        - bus booking
      summary: pre booking timeout
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                seat_name[]:
                  type: string
                  description: Bus Seat Name
                  example: GHA
                route_code:
                  type: string
                  description: Scheduled Bus Route Code
                  example: ktmmnr100
                association_code:
                  type: string
                  description: Scheduled Bus Association Code
                  example: m100
                date:
                  type: string
                  description: Scheduled Bus Date
                  example: '2080-02-32'
                time:
                  type: string
                  description: Scheduled Bus Time
                  example: '19:00'
                bus_facility_type_code:
                  type: string
                  description: Scheduled Bus Facility Type Code
                  example: ac100
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-booking:
    post:
      tags:
        - bus booking
      summary: store booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                route_code: ktmmnr100
                association_code: m100
                date: '2080-02-32'
                time: '19:00'
                bus_facility_type_code: ac100
                drop_location: drop location here
                rate: 15
                qty: 2
                discount: ''
                total: 30
                contact_name: Lal Bahadur
                contact_phone: '98713264'
                paid: ''
                due: ''
                return: ''
                bus_details: asdasd
                seat_name:
                  - D
                  - GHA
                payment_status: pending
                status: OnBooking
                t_price: 30
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-booking/{booking_id}/cancel:
    post:
      tags:
        - bus booking
      summary: cancel booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 51
                route_id: 1
                drop_location: drop location here
                rate: 2500
                qty: 4
                discount: ''
                total: 10000
                contact_name: Lal Bahadur
                contact_phone: '98713264'
                paid: ''
                due: ''
                return: ''
                bus_details: asdasd
                seat_id:
                  - '24'
                  - '35'
                  - '25'
                  - '36'
      security:
        - bearerAuth: []
      parameters:
        - name: booking_id
          in: path
          schema:
            type: integer
          required: true
          description: Bus Booking Id
          example: '544'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/my-booking:
    get:
      tags:
        - bus booking
      summary: my booking
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
